CREATE TABLE IF NOT EXISTS ping_metrics (
 id SERIAL PRIMARY KEY,
 target VARCHAR(255),
 rtt DOUBLE PRECISION,
 loss DOUBLE PRECISION,
 ts TIMESTAMP DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS http_metrics (
 id SERIAL PRIMARY KEY,
 target VARCHAR(255),
 path VARCHAR(255),
 response_time DOUBLE PRECISION,
 status_code INTEGER,
 ts TIMESTAMP DEFAULT NOW()
);